name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Build ZIP
        run: bash bin/build-zip.sh

      - name: List ZIP
        run: |
          echo "dist directory contents:"
          ls -lah dist || true

      - name: Check if WP.org SVN repo exists
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion
          if svn ls https://plugins.svn.wordpress.org/wp-post-exporter > /dev/null 2>&1; then
            echo "SVN_EXISTS=true" >> $GITHUB_ENV
          else
            echo "SVN_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: WordPress.org Plugin Deploy
        if: env.SVN_EXISTS == 'true'
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: false
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      - name: Dry-run deploy (SVN repo not found)
        if: env.SVN_EXISTS != 'true'
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: false
          dry-run: true
