name: PHPCS

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dev dependencies
        working-directory: wp-post-exporter
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run PHPCS
        working-directory: wp-post-exporter
        run: vendor/bin/phpcs -p

